erDiagram

    LogInfo {
    LogInfoType_t logInfoType 
    string logId
    string subLogId
    double cost
    double volume
    double price
    double preCost
    double preVolume
    double prePrice
    uint64_t timestamp
    uint64_t logCreatedTimestamp
    string subLogContent

}
  
